### ISSUE TITLE
Missing linker files for GCC & ARM

### ISSUE THREAD

**Issue by abudden** [STMicroelectronics/cmsis_device_h7#14]
**Describe the set-up**
 * The board: Nucleo-H723ZG
 * IDE: GCC (with cmake)

**Describe the bug**

In the folder "[Source/Templates](https://github.com/STMicroelectronics/cmsis_device_h7/tree/master/Source/Templates)" there are folders for each compiler.  Within these are linker files for those compilers.  In the [IAR linker folder](https://github.com/STMicroelectronics/cmsis_device_h7/tree/master/Source/Templates/iar/linker), there are linker files for a whole host of microcontrollers, including the STM32H723.  In the [GCC](https://github.com/STMicroelectronics/cmsis_device_h7/tree/master/Source/Templates/gcc/linker) and [ARM](https://github.com/STMicroelectronics/cmsis_device_h7/tree/master/Source/Templates/arm/linker) linker folders, there are far fewer and the STM32H723 is one of the ones missing.

The [startup code for GCC for the H723](https://github.com/STMicroelectronics/cmsis_device_h7/blob/master/Source/Templates/gcc/startup_stm32h723xx.s) is present [in the folder above](https://github.com/STMicroelectronics/cmsis_device_h7/tree/master/Source/Templates/gcc), so it seems strange that a corresponding linker file would not be included (or instructions on how to convert the provided IAR ICF linker file to GCC format).

**How To Reproduce**
1. Go to repository

2. Look for the GCC linker file for an STM32H723ZG

**Comment by TOUNSTM** [comment]
Hello @abudden,

Thank you for your contribution. GCC linker files can now be created using the CubeIDE project generator. You can also found them under STM32CubeIDE projects.
Unfortunately, our development teams have no plan to add new GCC linker files.

Please allow me to close this issue now. Thank you once again for your contribution and thank you for your comprehension.

With Regards,
