### ISSUE TITLE
Usage clarification: KEYR1 and KEYR2 Flash Registers

### ISSUE THREAD

**Issue by Steccah** [STMicroelectronics/cmsis_device_h7#6]
[KEYR1](https://github.com/STMicroelectronics/cmsis_device_h7/blob/902450ef44d7b4c0595b7620bda8a2ef705ef181/Include/stm32h743xx.h#L942C77-L942C77)
[KEYR2](https://github.com/STMicroelectronics/cmsis_device_h7/blob/902450ef44d7b4c0595b7620bda8a2ef705ef181/Include/stm32h743xx.h#L918)
Here KEYR1 and KEYR2 Flash registers are marked as IO (Read and write) but reference manual RM0433 chapters 4.9.2 and 4.9.24 say that should be write-only registers, is this right? If i try to read them from IAR ide the registers are always empty (0x00000000)

**Comment by TOUNSTM** [comment]
Hello @Steccah,

Thank you for your contribution. The KEYR1 and KEYR2 flash registers are write-only, and you are correct in highlighting this. Unfortunately, our development teams do not have immediate plans to implement a fix. It may be considered for future development. I will keep you updated on any changes in their plans.

Thank you once more for your report.

Kind regards,
